name: Sync with https://gitlab.freedesktop.org/libbsd/libbsd.git

on:
  #schedule:
  #  - cron: '0 0 */3 * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: master

    - name: Add upstream remote
      run: |
        git remote add source https://gitlab.freedesktop.org/libbsd/libbsd.git

    - name: Fetch upstream
      run: |
        git fetch source

    - name: Merge upstream main into master
      run: |
        git config user.name '[CI] libbsd mirror'
        git config user.email 'action@github.com'
        git checkout master
        git merge --allow-unrelated-histories source/main

    - name: Push mirror
      run: |
        git push origin master
